import Foundation

runMetricsCalculatorTests()
runMetricsFormatterTests()
runMetricBoundaryTests()
testNetworkCounterAccumulatorUnwrapsEachInterfaceBeforeSumming()
testNetworkCounterAccumulatorDoesNotTurnOrdinaryResetIntoTraffic()
testNetworkCounterAccumulatorKeepsTotalsMonotonicWhenInterfaceDeparts()
testNetworkCounterAccumulatorKeepsTotalsWhenAllInterfacesDepartAndRejoin()
try runMetricsHistoryTests()
runProcessTableTests()
runL10nTests()
finishTests()
