import Foundation

runMetricsCalculatorTests()
runMetricsFormatterTests()
runMetricBoundaryTests()
testNetworkCounterAccumulatorUnwrapsEachInterfaceBeforeSumming()
testNetworkCounterAccumulatorDoesNotTurnOrdinaryResetIntoTraffic()
try runMetricsHistoryTests()
finishTests()
